### PR TITLE
Echo version clusternode

### PR DESCRIPTION
**Pull request by tanxeel90**
echo version in cluster node to identify running versions for nodes in sys-cluster

### CODE REVIEW

**Comment by StanJav** [comment]
Looks fine @tanxeel90 

Would you mind pasting how the serialised string of `Version` type looks like?

**Comment by tanxeel90** [comment]
@StanJav 
```
 "EchoVersion": {
    "Major": 1,
    "Minor": 0,
    "Build": 0,
    "Revision": 0,
    "MajorRevision": 0,
    "MinorRevision": 0
  }
```

**Comment by StanJav** [comment]
Ah that is ugly. Could we change it to string? I do not see a reason to keep it like this.

**Comment by tanxeel90** [comment]
Closing this - the libs generated via nuget do not have a version number associated

**Pull request closed without merging**
