### PR TITLE
adds feature CancellationToken in message loop

### PR DESCRIPTION
**Pull request by StefanBertels**
Will allow reacting on kill/shutdown running.

Would solve my request #47.

In message look one can access SelfProcessCancellationToken (via Context) to get a cancellationToken for further use.

### CODE REVIEW

**Comment by louthy** [comment]
@StefanBertels Thanks for this, I appreciate you taking the time to get to the bottom of this.  I'd be interested in how much testing you've done (as there's no unit tests)?

**Comment by StefanBertels** [comment]
I have tested this with a small playground example and started using it. Works fine for now. But I'm not overlooking possible side effects. You should form your opinion on this -- with your general lib design / actor workflow in mind.

E.g.: I hope that the inbox directive (see commit f65c34b) is a good choice, but I'm not sure.

My use case is without backend cluster -- I just use the in-memory parts of echo (for now) and have my own persistence layer built on this.

Anyway: I will add unit tests (always a good thing).

**Comment by StefanBertels** [comment]
(Basic) unit tests added.

Open:  I'm not sure whether lock(sync) and CancellationToken must be considered in Actor.ProcessAsk.

Fixed: There was another race condition issue causing state initialized twice. I fixed this in fff2c86. The problem was that the first message "inbox1" arrived earlier at lock(sync) than the Startup-Message. 

I now see more clearly the life-time issue: Obviously sending a user message will always will result in setupFn to be called, so _every_  actor gets online this way -- probably even if started lazy.
This means that starting an actor un-lazy (default) will just cause setupFn to be called anyway/early.
That changes my view on #44 (see there)...

My unit test uses a small local helper function to wait for an actor to die (a little bit ugly because of task.delay). Maybe that could be useful as a general feature. But maybe kill(pid) will wait (and help with most use cases).

**Comment by louthy** [comment]
>  I hope that the inbox directive (see commit f65c34b) is a good choice, but I'm not sure

I think it's ok, but will probably need to be [in `ProcessAsk` too](https://github.com/louthy/echo-process/blob/f65c34ba10c012ae9f06b95d12feaabdff0806c5/Echo.Process/ActorSys/Actor.cs#L526
):

**Comment by StefanBertels** [comment]
Ok, added lock(sync) to ProcessAsk and fixed the (now more visible) shutdown race condition via cancellationToken -- similar to ProcessMessage. 

My solution uses replyError to inform the caller about the problem (actor is shutting down => inboxFn won't be processed). I'm not sure whether this is the best solution because any further ask message will run into timeout (because never getting out of pausableblockingqueue. Maybe just don't reply here? (In many cases the caller has to handle non-replying ask, anyway.) Or maybe reply with another error (same as timeout)?

**Comment by louthy** [comment]
In hindsight, this might be a bit more complex.

1) For non-persistent actors the message that is being processed should be sent to dead-letters.
2) For persistent actors it's arguable that the message should be placed back at the head of the queue, because the inbox hasn't processed it.

**Comment by StefanBertels** [comment]
I'm not sure what you mean.

1. AFAIK non-persistent actors get destroyed on shutdown, including inbox. So there is no user message queue after kill. Every message that was not consumed gets lost. Why should we handle the last message that was just passed to Actor but was not passed to inboxFn different? Actor shutdown is already in progress or already done. Seen from outside this message was just not processed after all.

2. I'm not familar with the cluster backend stuff, i.e. persistent actors. But should be same semantics. If  messages live in cluster space longer than actor life-time then they should stay there until processed.
"Until processed" means: inboxFn gets called (includes errors, but does not include our "cancelled" situation).
I had a short look at ActorInboxRemote and looks like InboxDirective.ShutDown does everything right: leave the GetNextMessage-loop without dequeueing.

**Comment by louthy** [comment]
Good points!  Sorry, been working about 50 projects at once ...  It's not always easy to keep it all in the head ;)

**Comment by louthy** [comment]
@StefanBertels  Thanks again for digging in to this.

**Comment by louthy** [comment]
Released in `v2.0.55`

**Pull request merged**
